### ISSUE TITLE
AsyncHook error: logrus hook can not send message before it is started

### ISSUE THREAD

**Issue by LuisAntezana** [misho-kr/logrus-hooks#3]
There is no way to do a `myAsyncHook.Start()` because, even if the function is public, the struct asyncHook is not. So nothing is calling the Start function and the error `logrus hook can not send message before it is started` keeps showing.

**Comment by misho-kr** [comment]
Thank you for finding this issue. The constructor function `AsyncHook()` was defined with incorrect return type which indeed created this problem.

This will be fixed with the changes in #4
